apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: fp
  labels:
    app: employees
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      serviceAccountName: clo835-sa
      containers:
      - name: webapp
        image: 788420915243.dkr.ecr.us-east-1.amazonaws.com/clo835-webapp:latest
        ports:
        - containerPort: 81
        env:
        - name: DBHOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DBHOST
        - name: DBPORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DBPORT
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DBUSER
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DBPWD
        - name: DATABASE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DATABASE
        - name: TEAM_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: TEAM_NAME
        - name: TEAM_SLOGAN
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: TEAM_SLOGAN
        - name: BACKGROUND_IMAGE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BACKGROUND_IMAGE_URL
        - name: S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: S3_BUCKET
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_SESSION_TOKEN          # ← ADD THIS
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_SESSION_TOKEN
      imagePullSecrets:
      - name: ecr-secret